#############################################
#           THM Make File Root directory   #
#############################################

install: tridiag.o
	gfortran -o tridiag_driver tridiag.o

tridiag.o : tridiag.f90
	fortran -c tridiag.f90
	
clean:
	rm tridiag.exe tridiag.0

tridiag_driver